# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'options_tag_filter_joiner.ui'
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets

class Ui_TagFilterJoiner(object):
    def setupUi(self, TagFilterJoiner):
        TagFilterJoiner.setObjectName("TagFilterJoiner")
        TagFilterJoiner.resize(700, 500)
        TagFilterJoiner.setMinimumSize(QtCore.QSize(500, 400))
        self.verticalLayout = QtWidgets.QVBoxLayout(TagFilterJoiner)
        self.verticalLayout.setObjectName("verticalLayout")
        self.description = QtWidgets.QLabel(TagFilterJoiner)
        self.description.setWordWrap(True)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.scrollArea = QtWidgets.QScrollArea(TagFilterJoiner)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 698, 69))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollLayout.setObjectName("scrollLayout")
        self.headerWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.headerWidget.setObjectName("headerWidget")
        self.headerLayout = QtWidgets.QHBoxLayout(self.headerWidget)
        self.headerLayout.setObjectName("headerLayout")
        self.tagHeader = QtWidgets.QLabel(self.headerWidget)
        self.tagHeader.setMinimumSize(QtCore.QSize(150, 0))
        self.tagHeader.setObjectName("tagHeader")
        self.headerLayout.addWidget(self.tagHeader)
        self.ignoreHeader = QtWidgets.QLabel(self.headerWidget)
        self.ignoreHeader.setMinimumSize(QtCore.QSize(80, 0))
        self.ignoreHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.ignoreHeader.setObjectName("ignoreHeader")
        self.headerLayout.addWidget(self.ignoreHeader)
        self.joinHeader = QtWidgets.QLabel(self.headerWidget)
        self.joinHeader.setMinimumSize(QtCore.QSize(120, 0))
        self.joinHeader.setAlignment(QtCore.Qt.AlignCenter)
        self.joinHeader.setObjectName("joinHeader")
        self.headerLayout.addWidget(self.joinHeader)
        self.separatorHeader = QtWidgets.QLabel(self.headerWidget)
        self.separatorHeader.setMinimumSize(QtCore.QSize(100, 0))
        self.separatorHeader.setObjectName("separatorHeader")
        self.headerLayout.addWidget(self.separatorHeader)
        self.scrollLayout.addWidget(self.headerWidget)
        self.tagsContainer = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.tagsContainer.setObjectName("tagsContainer")
        self.tagsLayout = QtWidgets.QVBoxLayout(self.tagsContainer)
        self.tagsLayout.setObjectName("tagsLayout")
        self.scrollLayout.addWidget(self.tagsContainer)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(TagFilterJoiner)
        QtCore.QMetaObject.connectSlotsByName(TagFilterJoiner)

    def retranslateUi(self, TagFilterJoiner):
        _translate = QtCore.QCoreApplication.translate
        TagFilterJoiner.setWindowTitle(_translate("TagFilterJoiner", "Form"))
        self.description.setText(_translate("TagFilterJoiner", "Configure which tags to ignore or join when they have multiple values."))
        self.tagHeader.setText(_translate("TagFilterJoiner", "<b>Tag</b>"))
        self.ignoreHeader.setText(_translate("TagFilterJoiner", "<b>Ignore</b>"))
        self.joinHeader.setText(_translate("TagFilterJoiner", "<b>Join Multi-values</b>"))
        self.separatorHeader.setText(_translate("TagFilterJoiner", "<b>Separator</b>"))