uuid = "b398e4bf-24f5-4ab5-a149-0ceacfb3cd32"
name = "Album Subfolder"
description = "After saving, moves files into a subfolder named 'Albumartist - Album'. Also moves artwork, cue sheets, and logs from the source folder. Requires 'Move additional files' to be DISABLED."
api = ["3.0"]
authors = ["rpmzine"]
license = "GPL-2.0-or-later"
license_url = "https://www.gnu.org/licenses/gpl-2.0.html"
repository = "https://github.com/rpmzine/picard-plugin-album-subfolder"
